Repository ghuyfel/flutter_azure_tts, pull requests merged in 2024-11, with the labels that each got.

#19 Support for styles and roles
  README.md
  example/lib/example.dart
  example/lib/main.dart
  lib/flutter_azure_tts.dart
  lib/src/audio/audio_handler.dart
  lib/src/audio/audio_request_param.dart
  lib/src/ssml/ssml.dart
  lib/src/tts/tts_params.dart
  lib/src/voices/voice_model.dart
  lib/src/voices/voice_model.g.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#22 Update README.md
  README.md
Labels: documentation

#23 bugfix/revert-package-name: fixed package name change
  CHANGELOG.md
  README.md
  example/lib/example.dart
  example/lib/main.dart
  lib/flutter_azure_tts.dart
  lib/src/audio/audio_handler.dart
  lib/src/audio/audio_request_param.dart
  lib/src/tts/tts_params.dart
  lib/src/voices/voice_data.dart
  lib/src/voices/voice_model.g.dart
  lib/src/voices/voice_roles.dart
  lib/src/voices/voice_styles.dart
  pubspec.yaml
Labels: bug
